In [1]:
import pymysql #Allows the connection to mysql
import pandas as pd #We need pandas to obtain a Data Frame
import getpass # function to prompt a cell to write down our password
from sqlalchemy import create_engine #Method to produce an engine based on a URL, that includes, host, user....

In [2]:
user = getpass.getuser()
password = getpass.getpass(prompt="Please enter your MySQL password",stream=None)
engine = create_engine('mysql+pymysql://{}:{}@localhost:3306/classicmodels'.format(user,password))
connection = pymysql.connect(host='localhost',user=user,password=password, db='classicmodels')

Please enter your MySQL password········

In [3]:
a="""SELECT * FROM employees;""" #Data frame from SQL

In [4]:
employees=pd.read_sql_query(a,engine)

In [5]:
df_employees =pd.DataFrame(employees)
df_employees.columns

Index(['employeeNumber', 'lastName', 'firstName', 'extension', 'email',
       'officeCode', 'reportsTo', 'jobTitle'],
      dtype='object')

In [6]:
df_employees['officeCode']=df_employees['officeCode'].astype(int)#Converting object into int to Vlookup

In [7]:
#Excel data frame, remeber to change directory to yours
df_offices=pd.read_excel('C:\\Users\\jose\\OneDrive - Dublin Business School (DBS)\\Desktop\\Files\\offices_2022-08-07.xlsx')

In [8]:
df_offices['officeCode']=df_offices['officeCode'].astype(int) #Converting object into int to Vlookup

In [9]:
df_offices.columns

Index(['officeCode', 'city', 'phone', 'addressLine1', 'addressLine2', 'state',
       'country', 'postalCode', 'territory'],
      dtype='object')

In [10]:
df_offices['officeCode']=df_offices['officeCode'].astype(int) #Converting object into int to Vlookup

In [11]:
#Vlookuping both data frames using officeCode as a unique identifier
#Here we are adding city and phone into df_employees
df_employees = pd.merge(df_employees,df_offices[['officeCode','city']],on='officeCode',how='left')
df_employees = pd.merge(df_employees,df_offices[['officeCode','phone']],on='officeCode',how='left')

In [12]:
df_employees

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,city,phone
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President,San Francisco,+1 650 219 4782
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales,San Francisco,+1 650 219 4782
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing,San Francisco,+1 650 219 4782
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC),Sydney,+61 2 9264 2451
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA),Paris,+33 14 723 4404
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056.0,Sales Manager (NA),San Francisco,+1 650 219 4782
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,San Francisco,+1 650 219 4782
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143.0,Sales Rep,San Francisco,+1 650 219 4782
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143.0,Sales Rep,Boston,+1 215 837 0825
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep,Boston,+1 215 837 0825
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143.0,Sales Rep,NYC,+1 212 555 3000
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143.0,Sales Rep,NYC,+1 212 555 3000
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102.0,Sales Rep,Paris,+33 14 723 4404
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep,Paris,+33 14 723 4404
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102.0,Sales Rep,Paris,+33 14 723 4404
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,London,+44 20 7877 2041
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep,London,+44 20 7877 2041
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088.0,Sales Rep,Sydney,+61 2 9264 2451
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088.0,Sales Rep,Sydney,+61 2 9264 2451
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088.0,Sales Rep,Sydney,+61 2 9264 2451
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056.0,Sales Rep,Tokyo,+81 33 224 5000
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621.0,Sales Rep,Tokyo,+81 33 224 5000
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102.0,Sales Rep,Paris,+33 14 723 4404